name: Build Docker Image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: flaugere/vscode:${{ steps.get_tag_name.outputs.TAG_NAME }}